version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        init: true
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mdb-vol:/var/lib/mysql
        restart: always

    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        init: true
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wp-vol:/var/www/html
        restart: always
  
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        init: true
        depends_on:
            - mariadb
        networks:
            - inception
        volumes:
            - wp-vol:/var/www/html
        env_file:
            - .env
        restart: always

networks:
    inception:
        name: inception

volumes:
    mdb-vol:
        name: mdb-vol
        driver: local
        driver_opts:
            device: /home/taelkhal/data/mariadb
            o: bind
            type: none
    wp-vol:
        name: wp-vol
        driver: local
        driver_opts:
            device: /home/taelkhal/data/wordpress
            o: bind
            type: none